"""
Utilities for Pauli-string preprocessing (Lie closure and structure constants).

This module provides helper routines for constructing dynamical Lie algebras
(DLAs) generated by Pauli strings represented with PauliEngine. It supports
two related but distinct use cases:

1. Single-Pauli generators
   Each generator is a single `pe.PauliString`. In this case, Lie closure can
   be computed efficiently using hash-based redundancy checks on compact integer
   signatures.

2. Sum-of-Pauli generators
   Each generator is a list of `pe.PauliString` objects representing a linear
   combination of Pauli monomials. In this case, linear dependence must be
   handled explicitly, and the module uses a sparse Gaussian-elimination style
   basis (`NormalizedBasis`) to maintain a normalized Lie basis.

The main public entry points are

- `lie_closure(...)`
    Compute only the closed Lie basis.
- `pauli_preprocessing(...)`
    Compute both the closed Lie basis and sparse structure-constant data.

Representation conventions
--------------------------
Internally, Pauli strings are encoded by compact immutable integer signatures
    ((q0, p0), (q1, p1), ...)
where each `qi` is a qubit index and each `pi` is an integer code:
`X -> 1`, `Y -> 2`, `Z -> 3`.

This avoids repeated string-based dictionary processing in hot loops and makes
set membership and sparse-vector manipulations efficient.

Adjoint / structure-constant format
-----------------------------------
The preprocessing routines return `adj_blocks`, a list of sparse commutator
slices. Entry `adj_blocks[gamma]` is a triple
    (u, v, f)
of NumPy arrays storing the nonzero coefficients associated with basis element
`gamma`. These arrays encode the raw commutator data used by the simulator
backend. Their exact sign convention matches the preprocessing routines in this
module and should therefore be treated as an internal storage format rather than
a user-facing mathematical object.

Notes
-----
- This module depends on `PauliEngine` for Pauli multiplication and commutators.
- Numerical coefficients smaller than `THRESHOLD` are discarded.
- The routines here are intended as low-level preprocessing primitives for the
  larger g-sim workflow.
"""

from itertools import product
from typing import List, Union, Tuple, Dict
import warnings
import numpy as np

import PauliEngine as pe

# -- globals --
THRESHOLD = 1e-12
_P2I = {'X': 1, 'Y': 2, 'Z': 3}
_I2P = {1: 'X', 2: 'Y', 3: 'Z'}

# --- utils ---

def sum_commutator(vec_A: Dict[Tuple, complex], vec_B: Dict[Tuple, complex]) \
        -> Dict[Tuple, complex]:
    """
    Compute the commutator of two sparse Pauli-sum vectors.

    Parameters
    ----------
    vec_A, vec_B : Dict[Tuple, complex]
        Sparse Pauli-sum representations mapping integer signatures to complex
        coefficients. Each key is a compact Pauli signature of the form
        `((qubit, pauli_code), ...)`.

    Returns
    -------
    Dict[Tuple, complex]
        Sparse dictionary encoding the commutator `[A, B]` in the same integer-
        signature format. Entries with magnitude below `THRESHOLD` are dropped.

    Notes
    -----
    This function is mainly a utility for the sum-of-Paulis workflow. It is not
    currently used in the hottest preprocessing loops, where additional caching
    is applied for performance.
    """

    commutator_vec = {}
    for (sig_a, coeff_a) in vec_A.items():
        for (sig_b, coeff_b) in vec_B.items():

            ps_a = pe.PauliString(dict(sig_a), 1.0)
            ps_b = pe.PauliString(dict(sig_b), 1.0)

            comm_res = ps_a.commutator(ps_b)
            c_expr, res_dict = comm_res.to_dictionary()
            factor = pe.PauliString.to_complex(c_expr)

            val = coeff_a * coeff_b * factor
            if abs(val) < THRESHOLD: continue

            res_sig = tuple(sorted((k, _P2I[v]) for k, v in res_dict.items()))
            commutator_vec[res_sig] = commutator_vec.get(res_sig, 0.0) + val

    return {k: v for k, v in commutator_vec.items() if abs(v) > THRESHOLD}

def _to_sparse_vector(pauli_list: List[pe.PauliString]) -> Dict[Tuple, complex]:
    """
    Convert a list of PauliEngine Pauli strings into a sparse signature vector.

    Parameters
    ----------
    pauli_list : List[pe.PauliString]
        List of Pauli strings, possibly with coefficients.

    Returns
    -------
    Dict[Tuple, complex]
        Sparse dictionary mapping compact integer signatures to accumulated
        complex coefficients.

    Notes
    -----
    This is the canonical conversion used throughout the module for the
    sum-of-Pauli workflow. Repeated signatures are merged, and coefficients
    smaller than `THRESHOLD` are discarded.
    """
    vec = {}
    for ps in pauli_list:
        c_expr, p_dict = ps.to_dictionary()
        c = pe.PauliString.to_complex(c_expr)
        if abs(c) < THRESHOLD: continue

        # Create a fast hashable integer signature: ((0, 1), (1, 3), ...)
        sig = tuple(sorted((k, _P2I[v]) for k, v in p_dict.items()))
        vec[sig] = vec.get(sig, 0.0) + c

    return {k: v for k, v in vec.items() if abs(v) > THRESHOLD}

class NormalizedBasis:
    """
    Sparse normalized basis with pivot-based elimination.

    This helper class maintains a normalized sparse basis of Pauli-sum vectors
    and supports decomposition of new vectors into

        vector = sum_i c_i * basis_i + remainder.

    It is used internally by the sum-of-Pauli closure and preprocessing
    routines to detect linear dependence and to normalize newly discovered Lie
    basis elements.

    Attributes
    ----------
    matrix : list[Dict[Tuple, complex]]
        List of normalized sparse basis vectors.
    pivots : list[Tuple]
        Pivot signature for each basis vector.
    """
    def __init__(self):
        self.matrix = []
        self.pivots = []

    def decompose(self, vector: Dict[Tuple, complex]) -> Tuple[Dict[int, float], Dict[Tuple, complex]]:
        """
        Decompose a sparse vector into the current basis plus a remainder.

        Parameters
        ----------
        vector : Dict[Tuple, complex]
            Sparse vector in integer-signature representation.

        Returns
        -------
        Tuple[Dict[int, float], Dict[Tuple, complex]]
            A pair `(coefficients, remainder)` where `coefficients` maps basis
            indices to expansion coefficients and `remainder` is the part not
            yet spanned by the current basis.

        Notes
        -----
        The coefficients are extracted during sparse Gaussian elimination using
        the stored pivot structure.
        """
        if not vector: return {}, {}

        candidate = vector.copy()
        coeffs = {}

        # Gaussian Elimination
        for i, (basis_vec, pivot_sig) in enumerate(zip(self.matrix, self.pivots)):
            if pivot_sig in candidate:
                factor = candidate[pivot_sig]

                if abs(factor) > 1e-9:
                    coeffs[i] = factor.imag

                for k, v in basis_vec.items():
                    candidate[k] = candidate.get(k, 0.0) - factor * v
                    if abs(candidate[k]) < 1e-9:
                        del candidate[k]

        return coeffs, candidate

    def insert_remainder(self, remainder: Dict[Tuple, complex]):
        """
        Normalize and append a new independent basis vector.

        Parameters
        ----------
        remainder : Dict[Tuple, complex]
            Nonzero sparse remainder returned by `decompose`.

        Returns
        -------
        Tuple[int, complex]
            `(new_index, normalization)` where `new_index` is the index of the
            inserted basis vector and `normalization` is the pivot value used to
            normalize it.

        Notes
        -----
        The new pivot is chosen as the lexicographically smallest signature
        present in the remainder.
        """
        sorted_keys = sorted(remainder.keys())
        new_pivot = sorted_keys[0]
        pivot_val = remainder[new_pivot]

        normalization = pivot_val
        normalized_vec = {k: v / normalization for k, v in remainder.items()}

        self.matrix.append(normalized_vec)
        self.pivots.append(new_pivot)

        return len(self.matrix) - 1, normalization

# --- main ---

def lie_closure(generators: Union[List[List[pe.PauliString]], List[pe.PauliString]],
                max_iterations: int = 10000,
                verbose: bool = False) \
        -> Union[List[List[pe.PauliString]], List[pe.PauliString]]:
    """
    Compute the Lie closure of a Pauli generating set.

    This wrapper dispatches automatically between the fast single-Pauli closure
    routine and the more general sum-of-Pauli closure routine.

    Parameters
    ----------
    generators : Union[List[List[pe.PauliString]], List[pe.PauliString]]
        Initial generating set.
        - `List[pe.PauliString]` for single Pauli monomials.
        - `List[List[pe.PauliString]]` for linear combinations of Pauli strings.
    max_iterations : int, optional
        Maximum number of closure epochs.
    verbose : bool, optional
        If `True`, print progress information.

    Returns
    -------
    Union[List[List[pe.PauliString]], List[pe.PauliString]]
        Closed Lie basis in the same structural format as the input.
    """
    if not generators:
        return []

    if isinstance(generators[0], list):
        return lie_closure_sums(generators, max_iterations, verbose)
    else:
        return lie_closure_singles(generators, max_iterations, verbose)


def lie_closure_sums(generators: List[List[pe.PauliString]],
                     max_iterations: int = 10000,
                     verbose: bool = False) -> List[List[pe.PauliString]]:
    """
    Compute the Lie closure for generators that are sums of Pauli strings.

    Parameters
    ----------
    generators : List[List[pe.PauliString]]
        Initial generating set, where each entry is a linear combination of
        Pauli strings.
    max_iterations : int, optional
        Maximum number of closure epochs.
    verbose : bool, optional
        If `True`, print progress information.

    Returns
    -------
    List[List[pe.PauliString]]
        Normalized Lie basis, represented as lists of PauliEngine Pauli strings.

    Notes
    -----
    This routine uses:
    - compact integer signatures for sparse-vector arithmetic,
    - a cache of unit-coefficient `PauliString` objects,
    - pivot-based elimination via `NormalizedBasis`.

    It is the appropriate closure routine whenever the generators are not
    guaranteed to remain linearly independent under commutation.
    """
    space = NormalizedBasis()
    ps_cache = {}

    def _get_cached_ps(sig):
        """Fetches or creates a pe.PauliString with coeff 1.0 from an integer signature."""
        if sig not in ps_cache:
            ps_cache[sig] = pe.PauliString({k: _I2P[v] for k, v in sig}, 1.0)
        return ps_cache[sig]

    for gen in generators:
        vec = _to_sparse_vector(gen)
        for sig in vec:
            _get_cached_ps(sig)

        _, remainder = space.decompose(vec)
        if remainder:
            space.insert_remainder(remainder)

    if verbose:
        print(f"Preprocessing done. Initial basis size: {len(space.matrix)}")

    epoch = 0
    old_len = 0
    new_len = len(space.matrix)

    while new_len > old_len and epoch < max_iterations:

        current_basis = space.matrix

        for alpha_idx in range(old_len, new_len):
            for beta_idx in range(alpha_idx):  # beta < alpha

                vec_A = current_basis[alpha_idx]
                vec_B = current_basis[beta_idx]

                commutator_vec = {}
                for (sig_a, coeff_a) in vec_A.items():
                    for (sig_b, coeff_b) in vec_B.items():

                        ps_a = _get_cached_ps(sig_a)
                        ps_b = _get_cached_ps(sig_b)

                        comm_res = ps_a.commutator(ps_b)
                        c_expr, res_dict = comm_res.to_dictionary()
                        factor = pe.PauliString.to_complex(c_expr)

                        val = coeff_a * coeff_b * factor
                        if abs(val) < THRESHOLD: continue

                        res_sig = tuple(sorted((k, _P2I[v]) for k, v in res_dict.items()))

                        if res_sig not in ps_cache:
                            ps_cache[res_sig] = pe.PauliString(res_dict, 1.0)

                        commutator_vec[res_sig] = commutator_vec.get(res_sig, 0.0) + val

                commutator_vec = {k: v for k, v in commutator_vec.items() if abs(v) > THRESHOLD}

                _, remainder = space.decompose(commutator_vec)

                if remainder:
                    space.insert_remainder(remainder)
                    if verbose:
                        print(f"New generator found. Basis size: {len(space.matrix)}")

        old_len = new_len
        new_len = len(space.matrix)
        epoch += 1

        if verbose:
            print(f"Epoch {epoch} complete. Basis size: {new_len}")

    if epoch == max_iterations:
        warnings.warn(f"Reached max iterations {max_iterations} in lie_closure_sums", UserWarning)

    final_basis = []
    for vec in space.matrix:
        op_list = []
        for sig, coeff in vec.items():
            c_clean = complex(round(coeff.real, 10), round(coeff.imag, 10))
            op_list.append(pe.PauliString({k: _I2P[v] for k, v in sig}, c_clean))
        final_basis.append(op_list)

    return final_basis


def lie_closure_singles(generators: List[pe.PauliString],
                        max_iterations: int = 10000,
                        verbose: bool = False) -> List[pe.PauliString]:
    """
    Compute the Lie closure of single Pauli-string generators.

    Parameters
    ----------
    generators : List[pe.PauliString]
        Initial generating set of single Pauli monomials.
    max_iterations : int, optional
        Maximum number of closure epochs.
    verbose : bool, optional
        If `True`, print progress information.

    Returns
    -------
    List[pe.PauliString]
        Closed Lie basis consisting of normalized single Pauli strings.

    Notes
    -----
    This routine is substantially faster than the sum-of-Pauli variant because
    linear dependence reduces to exact signature equality, which can be checked
    with a hash table.
    """
    g = generators.copy()
    g_lookup = {}

    for gen in g:
        gen.set_coeff(1)
        pauli_dict = gen.to_dictionary()[1]
        gen_key = tuple(sorted((k, _P2I[v]) for k, v in pauli_dict.items()))
        g_lookup[gen_key] = True

    if verbose:
        print(f'Preprocessing done. Initial basis size: {len(g)}')

    epoch = 0
    old_length = 0
    new_length = initial_length = len(g)

    while (new_length > old_length) and (epoch < max_iterations):
        for h1, h2 in product(g[old_length:], g[:initial_length]):
            com = h1.commutator(h2)

            coeff = com.get_coeff()
            if abs(pe.PauliString.to_complex(coeff)) < THRESHOLD:
                continue

            pauli_dict = com.to_dictionary()[1]

            h_key = tuple(sorted((k, _P2I[v]) for k, v in pauli_dict.items()))

            if h_key not in g_lookup:
                if verbose:
                    printable_key = tuple((k, _I2P[v]) for k, v in h_key)
                    print(f'New generator found: {printable_key}')

                com.set_coeff(1)
                g_lookup[h_key] = True
                g.append(com)

        old_length = new_length
        new_length = len(g)
        epoch += 1

        if verbose:
            print(f"Epoch {epoch} complete. Basis size: {new_length}")

        if epoch == max_iterations:
            warnings.warn(f"Reached the maximum number of iterations {max_iterations}", UserWarning)

    return g

def pauli_preprocessing(generators: Union[List[List[pe.PauliString]], List[pe.PauliString]],
                        max_iterations: int = 10000,
                        verbose: bool = False):
    """
    Compute both Lie closure and sparse structure-constant data.

    This wrapper dispatches automatically to the appropriate preprocessing
    routine depending on whether the generators are single Pauli strings or
    linear combinations of Pauli strings.

    Parameters
    ----------
    generators : Union[List[List[pe.PauliString]], List[pe.PauliString]]
        Initial generating set.
    max_iterations : int, optional
        Maximum number of closure epochs.
    verbose : bool, optional
        If `True`, print progress information.

    Returns
    -------
    basis : Union[List[List[pe.PauliString]], List[pe.PauliString]]
        Closed Lie basis in normalized form.
    adj_blocks : List[Tuple[np.ndarray, np.ndarray, np.ndarray]]
        Sparse commutator data used by later simulation routines.

    Notes
    -----
    The exact internal interpretation of `adj_blocks` depends on the chosen
    preprocessing routine and matches the downstream simulator conventions used
    in the codebase.
    """

    if not generators:
        return []

    if isinstance(generators[0], list):
        return pauli_sum_preprocessing(generators, max_iterations, verbose)
    else:
        return pauli_singles_preprocessing(generators, max_iterations, verbose)


def pauli_sum_preprocessing(generators: List[List[pe.PauliString]],
                            max_iterations: int = 10000,
                            verbose: bool = False):
    """
    Simultaneously compute Lie closure and sparse commutator data for Pauli sums.

    Parameters
    ----------
    generators : List[List[pe.PauliString]]
        Initial generating set, with each generator represented as a linear
        combination of Pauli strings.
    max_iterations : int, optional
        Maximum number of closure epochs.
    verbose : bool, optional
        If `True`, print progress information.

    Returns
    -------
    final_basis : List[List[pe.PauliString]]
        Closed, normalized Lie basis.
    adj_blocks : List[Tuple[np.ndarray, np.ndarray, np.ndarray]]
        Sparse commutator slices recorded during closure construction.

    Notes
    -----
    This routine performs closure and structure-constant recording in one pass.
    Newly discovered basis elements are normalized immediately and appended to
    the active basis.
    """
    space = NormalizedBasis()
    ps_cache = {}

    def _get_cached_ps(sig):
        """Fetches or creates a pe.PauliString with coeff 1.0 from an integer signature."""
        if sig not in ps_cache:
            ps_cache[sig] = pe.PauliString({k: _I2P[v] for k, v in sig}, 1.0)
        return ps_cache[sig]

    for gen in generators:
        vec = _to_sparse_vector(gen)
        for sig in vec:
            _get_cached_ps(sig)

        _, remainder = space.decompose(vec)
        if remainder:
            space.insert_remainder(remainder)

    initial_length = len(space.matrix)
    if verbose:
        print(f"Preprocessing done. Initial basis size: {initial_length}")

    adj_store = [{'u': [], 'v': [], 'f': []} for _ in range(initial_length)]

    epoch = 0
    old_len = 0
    new_len = initial_length

    while new_len > old_len and epoch < max_iterations:

        while len(adj_store) < new_len:
            adj_store.append({'u': [], 'v': [], 'f': []})

        current_basis = space.matrix

        for alpha_idx in range(old_len, new_len):
            for beta_idx in range(alpha_idx):

                vec_A = current_basis[alpha_idx]
                vec_B = current_basis[beta_idx]

                commutator_vec = {}
                for (sig_a, coeff_a) in vec_A.items():
                    for (sig_b, coeff_b) in vec_B.items():

                        ps_a = _get_cached_ps(sig_a)
                        ps_b = _get_cached_ps(sig_b)

                        comm_res = ps_a.commutator(ps_b)
                        c_expr, res_dict = comm_res.to_dictionary()
                        factor = pe.PauliString.to_complex(c_expr)

                        val = coeff_a * coeff_b * factor
                        if abs(val) < THRESHOLD: continue

                        res_sig = tuple(sorted((k, _P2I[v]) for k, v in res_dict.items()))

                        if res_sig not in ps_cache:
                            ps_cache[res_sig] = pe.PauliString(res_dict, 1.0)

                        commutator_vec[res_sig] = commutator_vec.get(res_sig, 0.0) + val

                commutator_vec = {k: v for k, v in commutator_vec.items() if abs(v) > THRESHOLD}
                coeffs, remainder = space.decompose(commutator_vec)

                if remainder:
                    new_idx, norm_factor = space.insert_remainder(remainder)
                    coeffs[new_idx] = norm_factor.imag

                    while len(adj_store) < len(space.matrix):
                        adj_store.append({'u': [], 'v': [], 'f': []})
                    if verbose:
                        print(f"New basis element found. Basis size: {len(space.matrix)}")

                for gamma_idx, f_val in coeffs.items():
                    if abs(f_val) > THRESHOLD:
                        adj_store[gamma_idx]['u'].append(beta_idx)
                        adj_store[gamma_idx]['v'].append(alpha_idx)
                        adj_store[gamma_idx]['f'].append(f_val)

        old_len = new_len
        new_len = len(space.matrix)
        epoch += 1

        if verbose:
            print(f"Epoch {epoch} complete. Basis size: {new_len}")

    if epoch == max_iterations:
        warnings.warn(f"Reached max iterations {max_iterations} in pauli_sum_preprocessing", UserWarning)

    final_basis = []
    for vec in space.matrix:
        op_list = []
        for sig, coeff in vec.items():
            c_clean = complex(round(coeff.real, 10), round(coeff.imag, 10))
            op_list.append(pe.PauliString({k: _I2P[v] for k, v in sig}, c_clean))
        final_basis.append(op_list)

    adj_blocks = []
    for store in adj_store:
        adj_blocks.append((
            np.array(store['u'], dtype=int),
            np.array(store['v'], dtype=int),
            np.array(store['f'], dtype=float)
        ))

    return final_basis, adj_blocks

def pauli_singles_preprocessing(generators: list[pe.PauliString],
                                max_iterations: int = 10000,
                                verbose: bool = False):
    """
    Simultaneously compute Lie closure and sparse commutator data for single Pauli generators.

    Parameters
    ----------
    generators : List[pe.PauliString]
        Initial generating set of Pauli monomials. Generators are normalized
        internally to unit coefficient.
    max_iterations : int, optional
        Maximum number of closure epochs.
    verbose : bool, optional
        If `True`, print progress information.

    Returns
    -------
    basis : List[pe.PauliString]
        Closed Lie basis of single Pauli strings.
    adj_blocks : List[Tuple[np.ndarray, np.ndarray, np.ndarray]]
        Sparse raw commutator data. Entry `adj_blocks[gamma]` stores arrays
        `(u, v, f)` associated with basis element `gamma`.

    Notes
    -----
    This function records commutator information on the fly during closure
    generation, avoiding a second pass over the final basis.
    """

    g = generators.copy()
    g_lookup = {}

    for i, gen in enumerate(g):
        gen.set_coeff(1)
        pauli_dict = gen.to_dictionary()[1]
        gen_key = tuple(sorted((k, _P2I[v]) for k, v in pauli_dict.items()))
        g_lookup[gen_key] = i

    initial_length = len(g)

    adj_blocks_u = [[] for _ in range(initial_length)]
    adj_blocks_v = [[] for _ in range(initial_length)]
    adj_blocks_f = [[] for _ in range(initial_length)]

    if verbose:
        print(f'Preprocessing done. Initial basis size: {len(g)}')

    epoch = 0
    old_length = 0
    new_length = initial_length

    while (new_length > old_length) and (epoch < max_iterations):

        for alpha_local, h1 in enumerate(g[old_length:]):
            alpha_global = old_length + alpha_local
            for beta_global in range(alpha_global):
                h2 = g[beta_global]
                com = h1.commutator(h2)
                coeff = pe.PauliString.to_complex(com.get_coeff())

                if abs(coeff) < 1e-9:
                    continue

                pauli_dict = com.to_dictionary()[1]
                h_key = tuple(sorted((k, _P2I[v]) for k, v in pauli_dict.items()))

                if h_key in g_lookup:
                    gamma = g_lookup[h_key]
                else:
                    if verbose:
                        print(f'New basis element found: {h_key}')
                    gamma = new_length

                    com.set_coeff(1)
                    g_lookup[h_key] = gamma
                    g.append(com)

                    adj_blocks_u.append([])
                    adj_blocks_v.append([])
                    adj_blocks_f.append([])

                val = coeff.imag

                adj_blocks_u[gamma].append(beta_global)
                adj_blocks_v[gamma].append(alpha_global)
                adj_blocks_f[gamma].append(-val)

        old_length = new_length
        new_length = len(g)
        epoch += 1

        if verbose:
            print(f"Epoch {epoch} complete. Basis size: {new_length}")

        if epoch == max_iterations:
            warnings.warn(f"Reached the maximum number of iterations {max_iterations}", UserWarning)

    adj_blocks = []
    for u, v, f in zip(adj_blocks_u, adj_blocks_v, adj_blocks_f):
        adj_blocks.append((
            np.array(u, dtype=int),
            np.array(v, dtype=int),
            np.array(f, dtype=float)
        ))

    return g, adj_blocks