"""
Helper routines for the free-fermionic TFIM g-sim experiment.

This module contains small, representation-specific utilities for the
freely-parameterized TFIM Hamiltonian variational ansatz (TFIM-HVA) used in
the numerical experiments. The implementation assumes the Pauli-string Lie
basis and the sparse 2x2-block structure of adjoint generators returned by
the `gsim.gstrings` preprocessing backend.

Main functionality
------------------
1. Construct the freely-parameterized TFIM generator set
   {Z_i Z_{i+1}} ∪ {X_i}.
2. Construct the matching coefficient vector for the TFIM Hamiltonian
   H = J sum_i Z_i Z_{i+1} - g sum_i X_i.
3. Apply adjoint-space rotations using the block structure of Pauli-string
   generator matrices.
4. Apply the corresponding infinitesimal adjoint action needed for
   reverse-mode gradient evaluation.

Notes
-----
- These helpers are specific to the TFIM experiment and not intended as a
  general Pauli-string simulation frontend.
- The block representation `(u, v, f)` is assumed to encode disjoint 2x2
  skew-symmetric blocks in the adjoint action of a Pauli-string generator.
"""

import numpy as np
from typing import Tuple
import PauliEngine as pe

def get_TFIM_generators(n: int, bounds='open'):
    """
    Return the freely-parameterized TFIM generator set on `n` qubits.

    Parameters
    ----------
    n : int
        Number of qubits.
    bounds : {'open', 'periodic'}, optional
        Boundary convention for the Ising couplings.

    Returns
    -------
    list[dict[int, str]]
        Generator list in operator-dictionary form, ordered as
        all nearest-neighbor `ZZ` terms first, followed by all single-qubit
        `X` terms.

    Notes
    -----
    For open boundaries, the returned set is
        {Z_i Z_{i+1}}_{i=0}^{n-2} ∪ {X_i}_{i=0}^{n-1}.
    For periodic boundaries, the wrap-around term `Z_{n-1} Z_0` is added.
    The returned ordering matches the coefficient convention of
    `get_TFIM_coefficients(...)`.
    """
    if bounds == 'periodic':
        generators = [{i:'Z', i+1:'Z'} for i in range(n - 1)] + [{n-1:'Z', 0:'Z'}]
    elif bounds == 'open':
        generators = [{i:'Z', i+1:'Z'} for i in range(n - 1)]
    else:
        raise ValueError(f'bounds must be either "open" or "periodic", not {bounds}.')
    generators += [{i:'X'} for i in range(n)]
    return generators

def get_TFIM_coefficients(n: int, g: float, J: float = 1.0, bounds='open'):
    """
    Return the TFIM Hamiltonian coefficients in generator order.

    Parameters
    ----------
    n : int
        Number of qubits.
    g : float
        Transverse-field strength.
    J : float, optional
        Ising coupling strength.
    bounds : {'open', 'periodic'}, optional
        Boundary convention for the Ising couplings.

    Returns
    -------
    list[float]
        Coefficients for the Hamiltonian
            H = J sum_i Z_i Z_{i+1} - g sum_i X_i
        in the same ordering as `get_TFIM_generators(...)`, i.e. all `ZZ`
        coefficients first and all `X` coefficients second.
    """
    if bounds == 'periodic':
        return [J] * n + [-g] * n
    else:
        return [J] * (n-1) + [-g] * n

def initial_expvector(g_basis: list[pe.PauliString], rho: str = 'plus'):
    """
    Efficiently constructs the sparse coefficient vector for the initial density matrix.

    This method avoids generating the full state space by strictly filtering the basis `g`
    for elements compatible with the chosen state (e.g., checking for 'X'/'I' purity for |+>).

    Parameters
    ----------
    g : list[pe.PauliString]
        The basis of the Lie Algebra.
    rho : str, default='plus'
        The initial state configuration.
        - 'plus': |+...><...+| (Compatible with I, X).
        - 'zero': |0...><...0| (Compatible with I, Z).

    Returns
    -------
    scipy.sparse.csr_matrix
        A sparse column vector of shape (len(g), 1) where non-zero entries represent
        basis elements present in the decomposition of rho.
    """

    if rho == 'plus':
        forbidden_chars = {'Y', 'Z'}  # If rho is 'plus' (|++++>), it consists only of I and X.
    elif rho == 'zero':
        forbidden_chars = {'X', 'Y'}  # If rho is 'zero' (|0000>), it consists only of I and Z.
    else:
        raise ValueError(f"The input state rho must be one of ['plus', 'zero'].")

    e_in = np.zeros(len(g_basis), dtype=float)

    for i, h_i in enumerate(g_basis):
        pauli_dict = h_i.to_dictionary()[1]
        if not (forbidden_chars & set(pauli_dict.values())):
            e_in[i] = 1.0

    return e_in

def pauli_expm_multiply(block_data: Tuple[np.ndarray, np.ndarray, np.ndarray],
                        vector: np.ndarray,
                        theta: float = 1):
    """
    Apply the adjoint-space rotation generated by one Pauli-string block matrix.

    Parameters
    ----------
    block_data : tuple[np.ndarray, np.ndarray, np.ndarray]
        Triple `(u, v, f)` describing disjoint 2x2 blocks of the adjoint
        generator. Each block acts as
            [[0, -f_k],
             [f_k,  0]]
        on the coordinate pair `(u_k, v_k)`.
    vector : np.ndarray
        Input/output adjoint-space vector, modified in place.
    theta : float, optional
        Rotation angle.

    Notes
    -----
    This routine exploits the fact that Pauli-string adjoint generators
    decompose into independent planar rotations, so the action of
        exp(theta * Adj[h])
    can be applied in O(dim(g)) time without forming a full matrix.
    """
    u, v, f = block_data

    thetas = f * theta
    c = np.cos(thetas)
    s = np.sin(thetas)
    val_u = vector[u]
    val_v = vector[v]

    vector[u] = c * val_u - s * val_v
    vector[v] = s * val_u + c * val_v

def pauli_undo_expm_multiply(block_data: Tuple[np.ndarray, np.ndarray, np.ndarray],
                            vector: np.ndarray,
                            theta: float = 1):
    """
    Apply the inverse adjoint-space rotation for one Pauli-string block matrix.

    Parameters
    ----------
    block_data : tuple[np.ndarray, np.ndarray, np.ndarray]
        Triple `(u, v, f)` describing the generator blocks.
    vector : np.ndarray
        Input/output adjoint-space vector, modified in place.
    theta : float, optional
        Rotation angle.

    Notes
    -----
    This implements
        vector <- exp(-theta * Adj[h]) @ vector
    and is used in the reverse sweep of the gradient calculation.
    """
    u, v, f = block_data

    thetas = f * theta
    c = np.cos(thetas)
    s = np.sin(thetas)
    val_u = vector[u]
    val_v = vector[v]

    vector[u] = c * val_u + s * val_v
    vector[v] = -s * val_u + c * val_v

def adj_multiply(block_data: Tuple[np.ndarray, np.ndarray, np.ndarray],
                 vector: np.ndarray):
    """
    Apply one Pauli-string adjoint generator to a vector.

    Parameters
    ----------
    block_data : tuple[np.ndarray, np.ndarray, np.ndarray]
        Triple `(u, v, f)` describing the nonzero 2x2 blocks.
    vector : np.ndarray
        Input adjoint-space vector.

    Returns
    -------
    np.ndarray
        The product `Adj[h] @ vector`.

    Notes
    -----
    Since the adjoint generator is zero outside the encoded 2x2 blocks, the
    multiplication can be carried out without constructing the full sparse or
    dense matrix.
    """
    new_vector = np.zeros_like(vector)

    u, v, f = block_data

    val_u = vector[u]
    val_v = vector[v]

    new_vector[u] = -f * val_v
    new_vector[v] = f * val_u

    return new_vector

def get_TFIM_ground_state_energy(n, J=1.0, g=1.0):
    """
    Compute the exact ground-state energy of the 1D open-boundary TFIM.

    The Hamiltonian is
        H = J sum_{i=1}^{n-1} Z_i Z_{i+1} - g sum_{i=1}^{n} X_i.

    The computation uses the free-fermionic / Majorana representation of the
    model, in which the quadratic Hamiltonian is encoded by a real
    antisymmetric `2n x 2n` matrix. The positive single-particle energies are
    obtained from the spectrum of `iA`, and the many-body ground-state energy
    is then
        E_0 = -1/2 sum_k eps_k.

    Parameters
    ----------
    n : int
        Number of spins in the chain.
    J : float, optional
        Nearest-neighbor Ising coupling strength.
    g : float, optional
        Transverse-field strength.

    Returns
    -------
    float
        Exact ground-state energy of the open-boundary TFIM.

    Notes
    -----
    This implementation scales polynomially in `n` and is practical for much
    larger system sizes than direct Hilbert-space diagonalization.
    """

    # Build 2n x 2n antisymmetric Majorana matrix A
    A = np.zeros((2*n, 2*n))

    # Transverse field terms:  -g X_i
    # Contribute coupling between gamma_{2i-1}, gamma_{2i}
    for i in range(n):
        A[2*i, 2*i+1] = 2*g
        A[2*i+1, 2*i] = -2*g

    # ZZ interaction terms: J Z_i Z_{i+1}
    # Couple gamma_{2i}, gamma_{2(i+1)-1}
    for i in range(n-1):
        A[2*i+1, 2*(i+1)] = 2*J
        A[2*(i+1), 2*i+1] = -2*J

    # Diagonalize iA (which is Hermitian)
    # Its eigenvalues come in ± pairs: ±ε_k
    eps = np.linalg.eigvalsh(1j * A)

    # Take positive eigenvalues only
    eps_pos = eps[eps > 1e-12]

    # Ground-state energy
    E0 = -0.5 * np.sum(eps_pos)

    return float(E0)